language: python
python:
  - '3.8.5'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="elearning.settings.travis"

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="elearning.settings.travis"

script:
  - ./manage.py test courses.tests.test_models
  - ./manage.py test courses.tests.test_views

branches:
  only:
    - dev